version: 0.2
env:
  variables:
    ECR_REPO_NAME: code-ecr
phases:
  pre_build:
    commands:
      - echo "hello"
      
      #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .
  post_build:
    commands:
      #step2 - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

      #step3  Generate image definitions file for ECS
      #step3 - printf '[{"name":"angular-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json

# step2        
#artifacts:
#  files:
#    - imagedefinitions.json